language: node_js
node_js: '0.10'
before_install:
- npm install -g grunt-cli
services:
- mongodb
deploy:
  provider: npm
  email: estevez.sylvain@gmail.com
  api_key:
    secure: Ofy1jV3BDamuAeoGos5uGC2Gd7gki+H2+c3LxjGdljOGBleFYFpyd2a54oo7M6y7FyFSbpKkr4SthGIuJRf4nsEntPXIfq1jN35lKBZWgz83JeJPQD+JE4l8BwOGmvvRqkjfhJDJW6Wz4y7R8l78JphwNfq1aKHGptW6Sas8pxc=
  on:
    tags: true
    all_branches: true